server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    # 是否需要将自己注册进注册中心
    register-with-eureka: true
    # 是否需要检索服务信息
    fetch-registry: true
  server:
    # 测试环境关闭自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false
    # 2秒间隔剔除一次
    eviction-interval-timer-in-ms: 2000
  instance:
    hostname: 127.0.0.1
spring:
  application:
    name: eureka-server
